version: '3.8'

services:
  jira:
    image: atlassian/jira-software:latest
    container_name: jira
    ports:
      - "8080:8080"
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://db:5432/jiradb
      - ATL_JDBC_USER=jirauser
      - ATL_JDBC_PASSWORD=jirapassword
      - ATL_DB_TYPE=postgres72
    volumes:
      - jira_data:/var/atlassian/jira
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: jira_db
    environment:
      POSTGRES_DB: jiradb
      POSTGRES_USER: jirauser
      POSTGRES_PASSWORD: jirapassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  jira_data:
  postgres_data: